homebrew_installed_packages:
  - asdf
  - awscli
  - azure-cli
  - cowsay
  - curl
  - docker-compose
  - gh
  - git
  - jq
  - netcat
  - pre-commit

homebrew_cask_apps:
  - alfred
  - arc
  - dbeaver-community
  - docker
  - ferdium
  - firefox
  - google-chrome
  - google-cloud-sdk
  - iterm2
  - microsoft-office
  - ngrok
  - obs
  - openvpn-connect
  - postman
  - pycharm
  - rectangle
  - the-unarchiver
  - utm
  - visual-studio-code
  - wireshark

dotfiles_repo: https://github.com/bartier/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/Personal/GitHub/dotfiles
dotfiles_files:
  - .zshrc
 # - .gitignore
 # - .osx
  - .vimrc


dockitems_remove:
  - 'App Store'
  - 'Calendar'
  - 'Contacts'
  - 'Downloads'
  - 'FaceTime'
  - 'Freeform'
  - 'Launchpad'
  - 'Mail'
  - 'Maps'
  - 'Messages'
  - 'Music'
  - 'Notes'
  - 'Photos'
  - 'Podcasts'
  - 'Reminders'
  - 'Safari'
  - 'System Settings'
  - 'TV'

osx_script: "~/.osx"
