---
- name: Configure host.
  hosts: all

  vars_files:
    - config.yml

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.dock
      tags: ['dock']
    # - role: geerlingguy.dotfiles
    #   tags: ['dotfiles']
