---
- name: Configure localhost
  hosts: localhost
  environment:
    PATH: "/opt/homebrew/bin:/opt/homebrew/sbin:{{ ansible_env.PATH }}"

  vars_files:
    - config.yml

  tasks:
    - name: Setup Homewbrew
      include_role:
        name: geerlingguy.mac.homebrew
      tags: homebrew

    - name: Setup dotfiles
      include_role:
        name: geerlingguy.dotfiles
      tags: dotfiles

    - name: Install Oh My ZSH
      ansible.builtin.shell: |
        if [ ! -d "/Users/$USER/.oh-my-zsh/" ]; then
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --keep-zshrc"
        fi
      tags: ohmyzsh

    - name: Install command-time plugin
      ansible.builtin.shell: |
        if [ ! -d "/Users/$USER/.oh-my-zsh/custom/plugins/command-time" ]; then
          git clone https://github.com/popstas/zsh-command-time.git /Users/$USER/.oh-my-zsh/custom/plugins/command-time
        fi
      tags: command-time

    - name: Install zsh-autosuggestions plugin
      ansible.builtin.shell: |
        if [ ! -d "/Users/$USER/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]; then
          git clone https://github.com/zsh-users/zsh-autosuggestions /Users/$USER/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        fi
      tags: zsh-autosuggestions

    - name: Install zsh-you-should-use plugin
      ansible.builtin.shell: |
        if [ ! -d "/Users/$USER/.oh-my-zsh/custom/plugins/you-should-use" ]; then
          git clone https://github.com/MichaelAquilina/zsh-you-should-use.git /Users/$USER/.oh-my-zsh/custom/plugins/you-should-use
        fi
      tags: zsh-autosuggestions


    - name: Install zsh-syntax-highlighting plugin
      ansible.builtin.shell: |
        if [ ! -d "/Users/$USER/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]; then
          git clone https://github.com/zsh-users/zsh-syntax-highlighting.git /Users/$USER/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        fi
      tags: zsh-autosuggestions

    - name: Setup Dock
      include_role:
        name: geerlingguy.mac.dock
      tags: dock

    - name: Install asdf plugins
      ansible.builtin.shell: |
        asdf plugin-add python
        asdf plugin-add terraform https://github.com/asdf-community/asdf-hashicorp.git
        asdf plugin-add kubectl https://github.com/asdf-community/asdf-kubectl.git
        asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
        asdf plugin add golang https://github.com/asdf-community/asdf-golang.git

        asdf install python latest
        asdf install terraform latest
        asdf install kubectl latest
        asdf install nodejs latest
        asdf install golang latest
      tags: asdf-plugins

    - name: Run .osx dotfile
      ansible.builtin.shell: |
        chmod +x {{ osx_script }} && {{ osx_script }}
      tags: osx
