---
- name: Configure localhost
  hosts: localhost

  vars_files:
    - config.yml

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    #TODO: Add brew path
    - role: geerlingguy.mac.dock
      tags: ['dock']
    - name: Restart Dock after geerlingguy.mac.dock execution to ensure settings are in place
      ansible.builtin.shell: killall Dock
    # - role: geerlingguy.dotfiles
    #   tags: ['dotfiles']
