---
- name: Configure localhost
  hosts: localhost

  vars_files:
    - config.yml

  # roles:
    # - role: geerlingguy.mac.homebrew
    #   tags: ['homebrew']

    #TODO: Maybe add Brew in PATH
    # - role: geerlingguy.mac.dock
    #   tags: ['dock']
    # - role: geerlingguy.dotfiles
    #   tags: ['dotfiles']
  tasks:
    - name: Setup Homewbrew
      include_role: geerlingguy.mac.homebrew

    - name: Setup Dock
      include_role: geerlingguy.mac.dock

    - name: Ensure Dock is running with latest changes
      shell: killall Dock
      tags: ['dock']
