---
- name: Configure localhost
  hosts: localhost

  vars_files:
    - config.yml

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    #TODO: Add brew path
    - role: geerlingguy.mac.dock
      tags: ['dock']
    # - role: geerlingguy.dotfiles
    #   tags: ['dotfiles']
