---
- name: Configure localhost
  hosts: localhost

  vars_files:
    - config.yml

  tasks:
    - name: Setup Homewbrew
      include_role:
        name: geerlingguy.mac.homebrew

    - name: Setup Dock
      include_role:
        name: geerlingguy.mac.dock

    - name: Ensure Dock is running with latest changes
      shell: killall Dock
      tags: ['dock']
