---
- name: Configure localhost
  hosts: localhost

  vars_files:
    - config.yml

  tasks:
    - name: Setup Homewbrew
      include_role:
        name: geerlingguy.mac.homebrew
      tags: homebrew

    - name: Setup dotfiles
      include_role:
        name: geerlingguy.dotfiles
      tags: dotfiles

    - name: Install Oh My ZSH
      ansible.builtin.shell: |
        if [ ! -d "~.oh-my-zsh/" ]; then
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --keep-zshrc"
        fi
      tags: ohmyzsh

    - name: Install zinit
      ansible.builtin.shell: |
        bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"
      tags: zinit

    - name: Install command-time plugin
      ansible.builtin.shell: |
        if [ ! -d "~/.oh-my-zsh/custom/plugins/command-time" ]; then
          git clone https://github.com/popstas/zsh-command-time.git ~/.oh-my-zsh/custom/plugins/command-time
        fi
      tags: command-time

    - name: Setup Dock
      include_role:
        name: geerlingguy.mac.dock
      tags: ['dock']

    # - name: Ensure Dock is running with latest changes
    #   shell: killall Dock
    #   tags: ['dock']

    # - name: Run .osx dotfile
    #   command: "{{ osx_script }}"
    #   become: yes
